---
title: Analyzing FC Barcelona's assists pattern
subtitle: "How to use the eurolig package to analyze the patterns in assists for FC Barcelona in this Euroleague season"
summary: "How to use the eurolig package to analyze the patterns in assists for FC Barcelona in this Euroleague season"
author: Sergio Olmos
date: '2019-03-28'
slug: analisis-asistencia
categories:
    - English
tags:
    - Basketball
    - Basketball analytics
    - R
image:
  caption: ''
  focal_point: ''
---



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p><a href="https://github.com/solmos/eurolig"><code>eurolig</code></a> is an R package that I just created for obtaining and analyzing basketball data games from the Euroleague. In this post I show how to use the package to analyze different aspects of the way FC Barcelona passes the ball in this Euroleague 2018-2019. More specifically, we are interested in finding out:</p>
<ol style="list-style-type: decimal">
<li><p>What type of shot each assist generates</p></li>
<li><p>How many points are being generated by each assist</p></li>
<li><p>Who assists who</p></li>
<li><p>How to visualize the patterns of assists</p></li>
</ol>
<hr />
</div>
<div id="eurolig" class="section level2">
<h2>eurolig</h2>
<p>The <code>eurolig</code> package is in its initial phase and still has many bugs. At the moment of writing, the package only provides tools to work with play-by-play data, but I hope to add the possibility to work with other types of data shuch as shot location data and regular boxscore stats.</p>
<p>The package can be installed from Github:</p>
<pre class="r"><code># install.packages(&quot;devtools&quot;)
devtools::install_github(&quot;solmos/eurolig&quot;)</code></pre>
<p>Note, however, that the package is in its experimental phase and there will be numerous changes as I keep developing it. Having said that, I encourage you to download the package and play around with it. If you detect a bug or think of useful feature, please let me know.</p>
<p>You can keep track of new features and releases in the <code>NEWS.md</code> file from the package <a href="https://github.com/solmos/eurolig">repository</a>.</p>
<hr />
</div>
<div id="analysis" class="section level2">
<h2>Analysis</h2>
<p>The play-by-play data allow us to answer many questions that cannot be answered with the regular boxscore data. In this case, we will use these type of data to answer the questions of interest that we introduced above.</p>
<div id="data-extraction" class="section level3">
<h3>Data extraction</h3>
<p>We can obtain the play-by-play data by entering the game code (or game codes) toguether with the starting year of the season we want into the <code>extract_pbp()</code> function.</p>
<p>The game code can be found in the URL of the game web page. For instance, the last game that FC Barcelona played in this Euroleague at the moment of writting was against Bayern Munich in the German city. The game URL is</p>
<p><a href="https://www.euroleague.net/main/results/showgame?gamecode=219&amp;seasoncode=E2018" class="uri">https://www.euroleague.net/main/results/showgame?gamecode=219&amp;seasoncode=E2018</a></p>
<p>We see that the game code is 219. Entering this code together with the corresponding year in <code>extract_pbp()</code> we obtain the play-by-play data in a tidy data frame:</p>
<pre class="r"><code>library(eurolig)
game_pbp &lt;- extract_pbp(game_code = 219, season = 2018)
game_pbp</code></pre>
<pre><code>## # A tibble: 518 x 18
##    game_code play_number team_code player_name play_type time_remaining
##    &lt;fct&gt;           &lt;int&gt; &lt;fct&gt;     &lt;fct&gt;       &lt;fct&gt;     &lt;chr&gt;         
##  1 219                 2 &lt;NA&gt;      &lt;NA&gt;        BP        10:00         
##  2 219                 3 MUN       RADOSEVIC,… TPOFF     09:59         
##  3 219                 4 BAR       TOMIC, ANTE TPOFF     09:59         
##  4 219                 5 BAR       RIBAS, PAU  3FGM      09:37         
##  5 219                 6 BAR       TOMIC, ANTE AS        09:35         
##  6 219                 7 MUN       LUCIC, VLA… 2FGA      09:20         
##  7 219                 8 BAR       TOMIC, ANTE D         09:18         
##  8 219                10 BAR       PANGOS, KE… 2FGA      08:58         
##  9 219                11 MUN       LUCIC, VLA… D         08:55         
## 10 219                12 MUN       JOVIC, STE… TO        08:34         
## # … with 508 more rows, and 12 more variables: quarter &lt;fct&gt;,
## #   points_home &lt;dbl&gt;, points_away &lt;dbl&gt;, team_name &lt;fct&gt;,
## #   player_id &lt;fct&gt;, player_dorsal &lt;dbl&gt;, play_info &lt;chr&gt;, seconds &lt;dbl&gt;,
## #   home_team &lt;fct&gt;, away_team &lt;fct&gt;, home &lt;lgl&gt;, season &lt;int&gt;</code></pre>
<p>In the present analysis we want to analyze more than just one game. Specifically, we want to obtain all the games FC Barcelona has played in this ongoing Euroleague. Instead of searching around the Euroleague website for all the different game codes, we can just use the function <code>extract_team_pbp()</code>. With this function we just need to enter the three letter team code and the year we want to obtain the data for all the games that the team has played in the given season.</p>
<p>Let’s proceed to download the data of the games that FC Barcelona has played so far (March 25, 2019):</p>
<pre class="r"><code>pbp &lt;- extract_team_pbp(team = &quot;BAR&quot;, season = 2018)</code></pre>
<p>Note that the process takes a relatively long time to return the final data frame. This in not a bug. The function is designed to be slow. The Euroleague’s API documentation asks to leave a few second between succesive requests.</p>
</div>
<div id="analysis-of-assists" class="section level3">
<h3>Analysis of assists</h3>
<p>To answer the diferent questions that we mentioned in the introduction we are going to use the function <code>get_assists()</code>. Entering the play-by-play data into this function we obtain a data frame with detailed information about each assist recorded in these games. This resulting data frame can be used to answer many interesting questions with just few lines of code.</p>
<pre class="r"><code>library(dplyr)
assists &lt;- get_assists(pbp, team = &quot;BAR&quot;)
assists</code></pre>
<pre><code>## # A tibble: 475 x 12
##    game_code season passer shooter shot_type points time_remaining quarter
##    &lt;fct&gt;     &lt;fct&gt;  &lt;fct&gt;  &lt;fct&gt;   &lt;fct&gt;      &lt;dbl&gt; &lt;chr&gt;          &lt;fct&gt;  
##  1 2         2018   HEURT… CLAVER… 2FG            1 09:43          1      
##  2 2         2018   CLAVE… TOMIC,… 2FG            2 08:39          1      
##  3 2         2018   HEURT… TOMIC,… 2FG            2 07:44          1      
##  4 2         2018   HEURT… SINGLE… 2FG            2 07:34          1      
##  5 2         2018   CLAVE… SINGLE… 2FG            3 03:19          1      
##  6 2         2018   ORIOL… SERAPH… 2FG            2 00:46          1      
##  7 2         2018   SERAP… KURIC,… 3FG            3 00:13          1      
##  8 2         2018   HEURT… ORIOLA… 2FG            2 07:08          2      
##  9 2         2018   HEURT… SERAPH… 2FG            2 04:58          2      
## 10 2         2018   BLAZI… PUSTOV… 2FG            2 01:17          2      
## # … with 465 more rows, and 4 more variables: seconds &lt;int&gt;, foul &lt;lgl&gt;,
## #   and1 &lt;dbl&gt;, ftm &lt;dbl&gt;</code></pre>
<div id="what-type-of-shot-each-player-generates-when-he-assists-a-teamate" class="section level4">
<h4>What type of shot each player generates when he assists a teamate?</h4>
<p>With the <code>assists</code> data frame we can find out what type of shot each assist leads to. An assists can lead to three point shot, a two point shot, a shooting foul (where at aleast one foul shot is made) or an <em>and 1</em>.</p>
<p>In this case, let’s say we are only interested in knowing whether the shot following an assist was a two or a three point shot. The FC Barcelona players with at least 10 assists total have distributed their assists as follows:</p>
<pre class="r"><code>assists %&gt;% 
    group_by(passer) %&gt;% 
    summarise(
        assists = n(),
        two_pointers = sum(shot_type == &quot;2FG&quot;, na.rm = TRUE),
        three_pointers = sum(shot_type == &quot;3FG&quot;, na.rm = TRUE),
        `3pt_ratio` = round(three_pointers / assists, 3)
    ) %&gt;% 
    arrange(desc(assists)) %&gt;% 
    filter(assists &gt; 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">passer</th>
<th align="right">assists</th>
<th align="right">two_pointers</th>
<th align="right">three_pointers</th>
<th align="right">3pt_ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">HEURTEL, THOMAS</td>
<td align="right">138</td>
<td align="right">101</td>
<td align="right">37</td>
<td align="right">0.268</td>
</tr>
<tr class="even">
<td align="left">PANGOS, KEVIN</td>
<td align="right">92</td>
<td align="right">55</td>
<td align="right">36</td>
<td align="right">0.391</td>
</tr>
<tr class="odd">
<td align="left">TOMIC, ANTE</td>
<td align="right">53</td>
<td align="right">34</td>
<td align="right">19</td>
<td align="right">0.358</td>
</tr>
<tr class="even">
<td align="left">RIBAS, PAU</td>
<td align="right">47</td>
<td align="right">33</td>
<td align="right">14</td>
<td align="right">0.298</td>
</tr>
<tr class="odd">
<td align="left">HANGA, ADAM</td>
<td align="right">30</td>
<td align="right">20</td>
<td align="right">10</td>
<td align="right">0.333</td>
</tr>
<tr class="even">
<td align="left">SINGLETON, CHRIS</td>
<td align="right">26</td>
<td align="right">15</td>
<td align="right">11</td>
<td align="right">0.423</td>
</tr>
<tr class="odd">
<td align="left">CLAVER, VICTOR</td>
<td align="right">23</td>
<td align="right">12</td>
<td align="right">11</td>
<td align="right">0.478</td>
</tr>
<tr class="even">
<td align="left">KURIC, KYLE</td>
<td align="right">21</td>
<td align="right">13</td>
<td align="right">8</td>
<td align="right">0.381</td>
</tr>
<tr class="odd">
<td align="left">ORIOLA, PIERRE</td>
<td align="right">15</td>
<td align="right">8</td>
<td align="right">7</td>
<td align="right">0.467</td>
</tr>
<tr class="even">
<td align="left">BLAZIC, JAKA</td>
<td align="right">12</td>
<td align="right">9</td>
<td align="right">3</td>
<td align="right">0.250</td>
</tr>
<tr class="odd">
<td align="left">SERAPHIN, KEVIN</td>
<td align="right">12</td>
<td align="right">8</td>
<td align="right">4</td>
<td align="right">0.333</td>
</tr>
</tbody>
</table>
<p>In this case, Heurtel has the second lowest ratio of assists to three pointers with respect total assists (0.268). On the other hand, Pangos has a substantially higher proportion of assists that lead to three pointers (0.391).</p>
<p>It’s the big and mobile players, like Claver, Singleton or Oriola, that have the highest proportion of assists going to three pointers.</p>
</div>
<div id="how-many-points-each-players-assists-generate" class="section level4">
<h4>How many points each player’s assists generate?</h4>
<p>As we have seen, not all assists are created equal. An assist to a three pointer generates two more points than an assist that results in a shooting foul where the shooter only scores one foul shot.</p>
<p>With the following lines of code we can compute how many points each player’s assists generated:</p>
<pre class="r"><code>assists %&gt;% 
    group_by(passer) %&gt;% 
    summarise(
        assists = n(),
        points = sum(points, na.rm = TRUE),
        ppa = round(points / assists, 3)
    ) %&gt;% 
    arrange(desc(assists)) %&gt;% 
    filter(assists &gt; 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">passer</th>
<th align="right">assists</th>
<th align="right">points</th>
<th align="right">ppa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">HEURTEL, THOMAS</td>
<td align="right">138</td>
<td align="right">311</td>
<td align="right">2.254</td>
</tr>
<tr class="even">
<td align="left">PANGOS, KEVIN</td>
<td align="right">92</td>
<td align="right">215</td>
<td align="right">2.337</td>
</tr>
<tr class="odd">
<td align="left">TOMIC, ANTE</td>
<td align="right">53</td>
<td align="right">121</td>
<td align="right">2.283</td>
</tr>
<tr class="even">
<td align="left">RIBAS, PAU</td>
<td align="right">47</td>
<td align="right">105</td>
<td align="right">2.234</td>
</tr>
<tr class="odd">
<td align="left">HANGA, ADAM</td>
<td align="right">30</td>
<td align="right">68</td>
<td align="right">2.267</td>
</tr>
<tr class="even">
<td align="left">SINGLETON, CHRIS</td>
<td align="right">26</td>
<td align="right">63</td>
<td align="right">2.423</td>
</tr>
<tr class="odd">
<td align="left">CLAVER, VICTOR</td>
<td align="right">23</td>
<td align="right">58</td>
<td align="right">2.522</td>
</tr>
<tr class="even">
<td align="left">KURIC, KYLE</td>
<td align="right">21</td>
<td align="right">48</td>
<td align="right">2.286</td>
</tr>
<tr class="odd">
<td align="left">ORIOLA, PIERRE</td>
<td align="right">15</td>
<td align="right">36</td>
<td align="right">2.400</td>
</tr>
<tr class="even">
<td align="left">BLAZIC, JAKA</td>
<td align="right">12</td>
<td align="right">26</td>
<td align="right">2.167</td>
</tr>
<tr class="odd">
<td align="left">SERAPHIN, KEVIN</td>
<td align="right">12</td>
<td align="right">28</td>
<td align="right">2.333</td>
</tr>
</tbody>
</table>
<p>The last column of this data frame (<code>ppa</code>) tells us how many Points Per Assist each player from FC Barcelona generates (with at least 10 assists). We observe that Claver and Singleton generate the highest value per assist, indicating that a relatively high proportion of their assists lead to a three point shot.</p>
</div>
<div id="who-assists-who" class="section level4">
<h4>Who assists who?</h4>
<p>With play-by-play data, it is also possible to find out to whom each player’s assist go to. The ten most common combinations passer-shooter are shown below:</p>
<pre class="r"><code>assists %&gt;% 
    group_by(passer, shooter) %&gt;% 
    count() %&gt;% 
    arrange(desc(n)) %&gt;% 
    head(10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">passer</th>
<th align="left">shooter</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">HEURTEL, THOMAS</td>
<td align="left">SERAPHIN, KEVIN</td>
<td align="right">27</td>
</tr>
<tr class="even">
<td align="left">HEURTEL, THOMAS</td>
<td align="left">TOMIC, ANTE</td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td align="left">PANGOS, KEVIN</td>
<td align="left">TOMIC, ANTE</td>
<td align="right">22</td>
</tr>
<tr class="even">
<td align="left">HEURTEL, THOMAS</td>
<td align="left">ORIOLA, PIERRE</td>
<td align="right">21</td>
</tr>
<tr class="odd">
<td align="left">HEURTEL, THOMAS</td>
<td align="left">SINGLETON, CHRIS</td>
<td align="right">17</td>
</tr>
<tr class="even">
<td align="left">PANGOS, KEVIN</td>
<td align="left">KURIC, KYLE</td>
<td align="right">16</td>
</tr>
<tr class="odd">
<td align="left">PANGOS, KEVIN</td>
<td align="left">SERAPHIN, KEVIN</td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left">TOMIC, ANTE</td>
<td align="left">SINGLETON, CHRIS</td>
<td align="right">15</td>
</tr>
<tr class="odd">
<td align="left">HEURTEL, THOMAS</td>
<td align="left">CLAVER, VICTOR</td>
<td align="right">12</td>
</tr>
<tr class="even">
<td align="left">HEURTEL, THOMAS</td>
<td align="left">KURIC, KYLE</td>
<td align="right">12</td>
</tr>
</tbody>
</table>
<p>The five most common combination passer-shooter are all from point guard to big man. We see that Heurtel connects very well with the bigs in his team, specially the two centers, Seraphin and Tomic. This explains the low proportion of assists to three point shots that we observed before.</p>
<p>However, in order to have a more accurate picture we would need to know how many minutes each combination was together on the floor. This information would allow us to identify potential improvements when deciding lineups.</p>
</div>
<div id="how-to-visualize-assists" class="section level4">
<h4>How to visualize assists</h4>
<p>It is possible to summarise some of the data that we obtained before using a heatmap showing the distribution of assists among the players of FC Barcelona. The function <code>plot_heatmap()</code> does just that:</p>
<pre class="r"><code>plot_heatmap(pbp, &quot;BAR&quot;) +
    ggplot2::labs(
        title = &quot;FC Barcelona assist heatmap&quot;,
        subtitle = &quot;Euroleague 2018-2019 (first 28 games)&quot;,
        x = &quot;Shooter&quot;,
        y = &quot;Passer&quot;)</code></pre>
<p><img src="/post/2019-03-28-análisis-asistencia/index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The vertical axis represents the passer while the horizontal axis represents the player that shoots after the pass. The diagonal contains the total number of assists for each player. The color indicates the number of assists that a given player gives to other player.</p>
</div>
</div>
</div>
